# site settings
title: Samsara
subtitle: by Véro + John
email: youremailaddress@gmail.com
description: Travel adventures and field notes of <br /> Véro + John.
baseurl: "/samsara" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/ohjho
googleplus_url:
instagram_url: https://instagram.com/johnho.ca
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
